// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.ones.openplatform.protocol;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlatformMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.PlatformMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * MessageHeader
     * </pre>
     *
     * <code>.protocol.RouterMessage Header = 1;</code>
     * @return Whether the header field is set.
     */
    boolean hasHeader();
    /**
     * <pre>
     * MessageHeader
     * </pre>
     *
     * <code>.protocol.RouterMessage Header = 1;</code>
     * @return The header.
     */
    com.ones.openplatform.protocol.Common.RouterMessage getHeader();
    /**
     * <pre>
     * MessageHeader
     * </pre>
     *
     * <code>.protocol.RouterMessage Header = 1;</code>
     */
    com.ones.openplatform.protocol.Common.RouterMessageOrBuilder getHeaderOrBuilder();

    /**
     * <pre>
     * body
     * </pre>
     *
     * <code>.protocol.ControlMessage Control = 5;</code>
     * @return Whether the control field is set.
     */
    boolean hasControl();
    /**
     * <pre>
     * body
     * </pre>
     *
     * <code>.protocol.ControlMessage Control = 5;</code>
     * @return The control.
     */
    com.ones.openplatform.protocol.Control.ControlMessage getControl();
    /**
     * <pre>
     * body
     * </pre>
     *
     * <code>.protocol.ControlMessage Control = 5;</code>
     */
    com.ones.openplatform.protocol.Control.ControlMessageOrBuilder getControlOrBuilder();

    /**
     * <code>.protocol.PluginMessage Plugin = 10;</code>
     * @return Whether the plugin field is set.
     */
    boolean hasPlugin();
    /**
     * <code>.protocol.PluginMessage Plugin = 10;</code>
     * @return The plugin.
     */
    com.ones.openplatform.protocol.Plugin.PluginMessage getPlugin();
    /**
     * <code>.protocol.PluginMessage Plugin = 10;</code>
     */
    com.ones.openplatform.protocol.Plugin.PluginMessageOrBuilder getPluginOrBuilder();

    /**
     * <code>.protocol.CmdbMessage Cmdb = 15;</code>
     * @return Whether the cmdb field is set.
     */
    boolean hasCmdb();
    /**
     * <code>.protocol.CmdbMessage Cmdb = 15;</code>
     * @return The cmdb.
     */
    com.ones.openplatform.protocol.Cmdb.CmdbMessage getCmdb();
    /**
     * <code>.protocol.CmdbMessage Cmdb = 15;</code>
     */
    com.ones.openplatform.protocol.Cmdb.CmdbMessageOrBuilder getCmdbOrBuilder();

    /**
     * <code>.protocol.ResourceMessage Resource = 20;</code>
     * @return Whether the resource field is set.
     */
    boolean hasResource();
    /**
     * <code>.protocol.ResourceMessage Resource = 20;</code>
     * @return The resource.
     */
    com.ones.openplatform.protocol.Resources.ResourceMessage getResource();
    /**
     * <code>.protocol.ResourceMessage Resource = 20;</code>
     */
    com.ones.openplatform.protocol.Resources.ResourceMessageOrBuilder getResourceOrBuilder();

    /**
     * <code>.protocol.NotifyMessage Notify = 25;</code>
     * @return Whether the notify field is set.
     */
    boolean hasNotify();
    /**
     * <code>.protocol.NotifyMessage Notify = 25;</code>
     * @return The notify.
     */
    com.ones.openplatform.protocol.Notify.NotifyMessage getNotify();
    /**
     * <code>.protocol.NotifyMessage Notify = 25;</code>
     */
    com.ones.openplatform.protocol.Notify.NotifyMessageOrBuilder getNotifyOrBuilder();
  }
  /**
   * Protobuf type {@code protocol.PlatformMessage}
   */
  public static final class PlatformMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.PlatformMessage)
      PlatformMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlatformMessage.newBuilder() to construct.
    private PlatformMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlatformMessage() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlatformMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlatformMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.ones.openplatform.protocol.Common.RouterMessage.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(com.ones.openplatform.protocol.Common.RouterMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.ones.openplatform.protocol.Control.ControlMessage.Builder subBuilder = null;
              if (control_ != null) {
                subBuilder = control_.toBuilder();
              }
              control_ = input.readMessage(com.ones.openplatform.protocol.Control.ControlMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(control_);
                control_ = subBuilder.buildPartial();
              }

              break;
            }
            case 82: {
              com.ones.openplatform.protocol.Plugin.PluginMessage.Builder subBuilder = null;
              if (plugin_ != null) {
                subBuilder = plugin_.toBuilder();
              }
              plugin_ = input.readMessage(com.ones.openplatform.protocol.Plugin.PluginMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(plugin_);
                plugin_ = subBuilder.buildPartial();
              }

              break;
            }
            case 122: {
              com.ones.openplatform.protocol.Cmdb.CmdbMessage.Builder subBuilder = null;
              if (cmdb_ != null) {
                subBuilder = cmdb_.toBuilder();
              }
              cmdb_ = input.readMessage(com.ones.openplatform.protocol.Cmdb.CmdbMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cmdb_);
                cmdb_ = subBuilder.buildPartial();
              }

              break;
            }
            case 162: {
              com.ones.openplatform.protocol.Resources.ResourceMessage.Builder subBuilder = null;
              if (resource_ != null) {
                subBuilder = resource_.toBuilder();
              }
              resource_ = input.readMessage(com.ones.openplatform.protocol.Resources.ResourceMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resource_);
                resource_ = subBuilder.buildPartial();
              }

              break;
            }
            case 202: {
              com.ones.openplatform.protocol.Notify.NotifyMessage.Builder subBuilder = null;
              if (notify_ != null) {
                subBuilder = notify_.toBuilder();
              }
              notify_ = input.readMessage(com.ones.openplatform.protocol.Notify.NotifyMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(notify_);
                notify_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ones.openplatform.protocol.Message.internal_static_protocol_PlatformMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ones.openplatform.protocol.Message.internal_static_protocol_PlatformMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ones.openplatform.protocol.Message.PlatformMessage.class, com.ones.openplatform.protocol.Message.PlatformMessage.Builder.class);
    }

    public static final int HEADER_FIELD_NUMBER = 1;
    private com.ones.openplatform.protocol.Common.RouterMessage header_;
    /**
     * <pre>
     * MessageHeader
     * </pre>
     *
     * <code>.protocol.RouterMessage Header = 1;</code>
     * @return Whether the header field is set.
     */
    @java.lang.Override
    public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <pre>
     * MessageHeader
     * </pre>
     *
     * <code>.protocol.RouterMessage Header = 1;</code>
     * @return The header.
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Common.RouterMessage getHeader() {
      return header_ == null ? com.ones.openplatform.protocol.Common.RouterMessage.getDefaultInstance() : header_;
    }
    /**
     * <pre>
     * MessageHeader
     * </pre>
     *
     * <code>.protocol.RouterMessage Header = 1;</code>
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Common.RouterMessageOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int CONTROL_FIELD_NUMBER = 5;
    private com.ones.openplatform.protocol.Control.ControlMessage control_;
    /**
     * <pre>
     * body
     * </pre>
     *
     * <code>.protocol.ControlMessage Control = 5;</code>
     * @return Whether the control field is set.
     */
    @java.lang.Override
    public boolean hasControl() {
      return control_ != null;
    }
    /**
     * <pre>
     * body
     * </pre>
     *
     * <code>.protocol.ControlMessage Control = 5;</code>
     * @return The control.
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Control.ControlMessage getControl() {
      return control_ == null ? com.ones.openplatform.protocol.Control.ControlMessage.getDefaultInstance() : control_;
    }
    /**
     * <pre>
     * body
     * </pre>
     *
     * <code>.protocol.ControlMessage Control = 5;</code>
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Control.ControlMessageOrBuilder getControlOrBuilder() {
      return getControl();
    }

    public static final int PLUGIN_FIELD_NUMBER = 10;
    private com.ones.openplatform.protocol.Plugin.PluginMessage plugin_;
    /**
     * <code>.protocol.PluginMessage Plugin = 10;</code>
     * @return Whether the plugin field is set.
     */
    @java.lang.Override
    public boolean hasPlugin() {
      return plugin_ != null;
    }
    /**
     * <code>.protocol.PluginMessage Plugin = 10;</code>
     * @return The plugin.
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Plugin.PluginMessage getPlugin() {
      return plugin_ == null ? com.ones.openplatform.protocol.Plugin.PluginMessage.getDefaultInstance() : plugin_;
    }
    /**
     * <code>.protocol.PluginMessage Plugin = 10;</code>
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Plugin.PluginMessageOrBuilder getPluginOrBuilder() {
      return getPlugin();
    }

    public static final int CMDB_FIELD_NUMBER = 15;
    private com.ones.openplatform.protocol.Cmdb.CmdbMessage cmdb_;
    /**
     * <code>.protocol.CmdbMessage Cmdb = 15;</code>
     * @return Whether the cmdb field is set.
     */
    @java.lang.Override
    public boolean hasCmdb() {
      return cmdb_ != null;
    }
    /**
     * <code>.protocol.CmdbMessage Cmdb = 15;</code>
     * @return The cmdb.
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Cmdb.CmdbMessage getCmdb() {
      return cmdb_ == null ? com.ones.openplatform.protocol.Cmdb.CmdbMessage.getDefaultInstance() : cmdb_;
    }
    /**
     * <code>.protocol.CmdbMessage Cmdb = 15;</code>
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Cmdb.CmdbMessageOrBuilder getCmdbOrBuilder() {
      return getCmdb();
    }

    public static final int RESOURCE_FIELD_NUMBER = 20;
    private com.ones.openplatform.protocol.Resources.ResourceMessage resource_;
    /**
     * <code>.protocol.ResourceMessage Resource = 20;</code>
     * @return Whether the resource field is set.
     */
    @java.lang.Override
    public boolean hasResource() {
      return resource_ != null;
    }
    /**
     * <code>.protocol.ResourceMessage Resource = 20;</code>
     * @return The resource.
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Resources.ResourceMessage getResource() {
      return resource_ == null ? com.ones.openplatform.protocol.Resources.ResourceMessage.getDefaultInstance() : resource_;
    }
    /**
     * <code>.protocol.ResourceMessage Resource = 20;</code>
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Resources.ResourceMessageOrBuilder getResourceOrBuilder() {
      return getResource();
    }

    public static final int NOTIFY_FIELD_NUMBER = 25;
    private com.ones.openplatform.protocol.Notify.NotifyMessage notify_;
    /**
     * <code>.protocol.NotifyMessage Notify = 25;</code>
     * @return Whether the notify field is set.
     */
    @java.lang.Override
    public boolean hasNotify() {
      return notify_ != null;
    }
    /**
     * <code>.protocol.NotifyMessage Notify = 25;</code>
     * @return The notify.
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Notify.NotifyMessage getNotify() {
      return notify_ == null ? com.ones.openplatform.protocol.Notify.NotifyMessage.getDefaultInstance() : notify_;
    }
    /**
     * <code>.protocol.NotifyMessage Notify = 25;</code>
     */
    @java.lang.Override
    public com.ones.openplatform.protocol.Notify.NotifyMessageOrBuilder getNotifyOrBuilder() {
      return getNotify();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      if (control_ != null) {
        output.writeMessage(5, getControl());
      }
      if (plugin_ != null) {
        output.writeMessage(10, getPlugin());
      }
      if (cmdb_ != null) {
        output.writeMessage(15, getCmdb());
      }
      if (resource_ != null) {
        output.writeMessage(20, getResource());
      }
      if (notify_ != null) {
        output.writeMessage(25, getNotify());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      if (control_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getControl());
      }
      if (plugin_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getPlugin());
      }
      if (cmdb_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, getCmdb());
      }
      if (resource_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(20, getResource());
      }
      if (notify_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(25, getNotify());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ones.openplatform.protocol.Message.PlatformMessage)) {
        return super.equals(obj);
      }
      com.ones.openplatform.protocol.Message.PlatformMessage other = (com.ones.openplatform.protocol.Message.PlatformMessage) obj;

      if (hasHeader() != other.hasHeader()) return false;
      if (hasHeader()) {
        if (!getHeader()
            .equals(other.getHeader())) return false;
      }
      if (hasControl() != other.hasControl()) return false;
      if (hasControl()) {
        if (!getControl()
            .equals(other.getControl())) return false;
      }
      if (hasPlugin() != other.hasPlugin()) return false;
      if (hasPlugin()) {
        if (!getPlugin()
            .equals(other.getPlugin())) return false;
      }
      if (hasCmdb() != other.hasCmdb()) return false;
      if (hasCmdb()) {
        if (!getCmdb()
            .equals(other.getCmdb())) return false;
      }
      if (hasResource() != other.hasResource()) return false;
      if (hasResource()) {
        if (!getResource()
            .equals(other.getResource())) return false;
      }
      if (hasNotify() != other.hasNotify()) return false;
      if (hasNotify()) {
        if (!getNotify()
            .equals(other.getNotify())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (hasControl()) {
        hash = (37 * hash) + CONTROL_FIELD_NUMBER;
        hash = (53 * hash) + getControl().hashCode();
      }
      if (hasPlugin()) {
        hash = (37 * hash) + PLUGIN_FIELD_NUMBER;
        hash = (53 * hash) + getPlugin().hashCode();
      }
      if (hasCmdb()) {
        hash = (37 * hash) + CMDB_FIELD_NUMBER;
        hash = (53 * hash) + getCmdb().hashCode();
      }
      if (hasResource()) {
        hash = (37 * hash) + RESOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getResource().hashCode();
      }
      if (hasNotify()) {
        hash = (37 * hash) + NOTIFY_FIELD_NUMBER;
        hash = (53 * hash) + getNotify().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ones.openplatform.protocol.Message.PlatformMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ones.openplatform.protocol.Message.PlatformMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ones.openplatform.protocol.Message.PlatformMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ones.openplatform.protocol.Message.PlatformMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ones.openplatform.protocol.Message.PlatformMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ones.openplatform.protocol.Message.PlatformMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ones.openplatform.protocol.Message.PlatformMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ones.openplatform.protocol.Message.PlatformMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ones.openplatform.protocol.Message.PlatformMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ones.openplatform.protocol.Message.PlatformMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ones.openplatform.protocol.Message.PlatformMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ones.openplatform.protocol.Message.PlatformMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ones.openplatform.protocol.Message.PlatformMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.PlatformMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.PlatformMessage)
        com.ones.openplatform.protocol.Message.PlatformMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ones.openplatform.protocol.Message.internal_static_protocol_PlatformMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ones.openplatform.protocol.Message.internal_static_protocol_PlatformMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ones.openplatform.protocol.Message.PlatformMessage.class, com.ones.openplatform.protocol.Message.PlatformMessage.Builder.class);
      }

      // Construct using com.ones.openplatform.protocol.Message.PlatformMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (controlBuilder_ == null) {
          control_ = null;
        } else {
          control_ = null;
          controlBuilder_ = null;
        }
        if (pluginBuilder_ == null) {
          plugin_ = null;
        } else {
          plugin_ = null;
          pluginBuilder_ = null;
        }
        if (cmdbBuilder_ == null) {
          cmdb_ = null;
        } else {
          cmdb_ = null;
          cmdbBuilder_ = null;
        }
        if (resourceBuilder_ == null) {
          resource_ = null;
        } else {
          resource_ = null;
          resourceBuilder_ = null;
        }
        if (notifyBuilder_ == null) {
          notify_ = null;
        } else {
          notify_ = null;
          notifyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ones.openplatform.protocol.Message.internal_static_protocol_PlatformMessage_descriptor;
      }

      @java.lang.Override
      public com.ones.openplatform.protocol.Message.PlatformMessage getDefaultInstanceForType() {
        return com.ones.openplatform.protocol.Message.PlatformMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.ones.openplatform.protocol.Message.PlatformMessage build() {
        com.ones.openplatform.protocol.Message.PlatformMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ones.openplatform.protocol.Message.PlatformMessage buildPartial() {
        com.ones.openplatform.protocol.Message.PlatformMessage result = new com.ones.openplatform.protocol.Message.PlatformMessage(this);
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (controlBuilder_ == null) {
          result.control_ = control_;
        } else {
          result.control_ = controlBuilder_.build();
        }
        if (pluginBuilder_ == null) {
          result.plugin_ = plugin_;
        } else {
          result.plugin_ = pluginBuilder_.build();
        }
        if (cmdbBuilder_ == null) {
          result.cmdb_ = cmdb_;
        } else {
          result.cmdb_ = cmdbBuilder_.build();
        }
        if (resourceBuilder_ == null) {
          result.resource_ = resource_;
        } else {
          result.resource_ = resourceBuilder_.build();
        }
        if (notifyBuilder_ == null) {
          result.notify_ = notify_;
        } else {
          result.notify_ = notifyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ones.openplatform.protocol.Message.PlatformMessage) {
          return mergeFrom((com.ones.openplatform.protocol.Message.PlatformMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ones.openplatform.protocol.Message.PlatformMessage other) {
        if (other == com.ones.openplatform.protocol.Message.PlatformMessage.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasControl()) {
          mergeControl(other.getControl());
        }
        if (other.hasPlugin()) {
          mergePlugin(other.getPlugin());
        }
        if (other.hasCmdb()) {
          mergeCmdb(other.getCmdb());
        }
        if (other.hasResource()) {
          mergeResource(other.getResource());
        }
        if (other.hasNotify()) {
          mergeNotify(other.getNotify());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ones.openplatform.protocol.Message.PlatformMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ones.openplatform.protocol.Message.PlatformMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.ones.openplatform.protocol.Common.RouterMessage header_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Common.RouterMessage, com.ones.openplatform.protocol.Common.RouterMessage.Builder, com.ones.openplatform.protocol.Common.RouterMessageOrBuilder> headerBuilder_;
      /**
       * <pre>
       * MessageHeader
       * </pre>
       *
       * <code>.protocol.RouterMessage Header = 1;</code>
       * @return Whether the header field is set.
       */
      public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <pre>
       * MessageHeader
       * </pre>
       *
       * <code>.protocol.RouterMessage Header = 1;</code>
       * @return The header.
       */
      public com.ones.openplatform.protocol.Common.RouterMessage getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? com.ones.openplatform.protocol.Common.RouterMessage.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * MessageHeader
       * </pre>
       *
       * <code>.protocol.RouterMessage Header = 1;</code>
       */
      public Builder setHeader(com.ones.openplatform.protocol.Common.RouterMessage value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * MessageHeader
       * </pre>
       *
       * <code>.protocol.RouterMessage Header = 1;</code>
       */
      public Builder setHeader(
          com.ones.openplatform.protocol.Common.RouterMessage.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * MessageHeader
       * </pre>
       *
       * <code>.protocol.RouterMessage Header = 1;</code>
       */
      public Builder mergeHeader(com.ones.openplatform.protocol.Common.RouterMessage value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              com.ones.openplatform.protocol.Common.RouterMessage.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * MessageHeader
       * </pre>
       *
       * <code>.protocol.RouterMessage Header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * MessageHeader
       * </pre>
       *
       * <code>.protocol.RouterMessage Header = 1;</code>
       */
      public com.ones.openplatform.protocol.Common.RouterMessage.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * MessageHeader
       * </pre>
       *
       * <code>.protocol.RouterMessage Header = 1;</code>
       */
      public com.ones.openplatform.protocol.Common.RouterMessageOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              com.ones.openplatform.protocol.Common.RouterMessage.getDefaultInstance() : header_;
        }
      }
      /**
       * <pre>
       * MessageHeader
       * </pre>
       *
       * <code>.protocol.RouterMessage Header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Common.RouterMessage, com.ones.openplatform.protocol.Common.RouterMessage.Builder, com.ones.openplatform.protocol.Common.RouterMessageOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ones.openplatform.protocol.Common.RouterMessage, com.ones.openplatform.protocol.Common.RouterMessage.Builder, com.ones.openplatform.protocol.Common.RouterMessageOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private com.ones.openplatform.protocol.Control.ControlMessage control_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Control.ControlMessage, com.ones.openplatform.protocol.Control.ControlMessage.Builder, com.ones.openplatform.protocol.Control.ControlMessageOrBuilder> controlBuilder_;
      /**
       * <pre>
       * body
       * </pre>
       *
       * <code>.protocol.ControlMessage Control = 5;</code>
       * @return Whether the control field is set.
       */
      public boolean hasControl() {
        return controlBuilder_ != null || control_ != null;
      }
      /**
       * <pre>
       * body
       * </pre>
       *
       * <code>.protocol.ControlMessage Control = 5;</code>
       * @return The control.
       */
      public com.ones.openplatform.protocol.Control.ControlMessage getControl() {
        if (controlBuilder_ == null) {
          return control_ == null ? com.ones.openplatform.protocol.Control.ControlMessage.getDefaultInstance() : control_;
        } else {
          return controlBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * body
       * </pre>
       *
       * <code>.protocol.ControlMessage Control = 5;</code>
       */
      public Builder setControl(com.ones.openplatform.protocol.Control.ControlMessage value) {
        if (controlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          control_ = value;
          onChanged();
        } else {
          controlBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * body
       * </pre>
       *
       * <code>.protocol.ControlMessage Control = 5;</code>
       */
      public Builder setControl(
          com.ones.openplatform.protocol.Control.ControlMessage.Builder builderForValue) {
        if (controlBuilder_ == null) {
          control_ = builderForValue.build();
          onChanged();
        } else {
          controlBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * body
       * </pre>
       *
       * <code>.protocol.ControlMessage Control = 5;</code>
       */
      public Builder mergeControl(com.ones.openplatform.protocol.Control.ControlMessage value) {
        if (controlBuilder_ == null) {
          if (control_ != null) {
            control_ =
              com.ones.openplatform.protocol.Control.ControlMessage.newBuilder(control_).mergeFrom(value).buildPartial();
          } else {
            control_ = value;
          }
          onChanged();
        } else {
          controlBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * body
       * </pre>
       *
       * <code>.protocol.ControlMessage Control = 5;</code>
       */
      public Builder clearControl() {
        if (controlBuilder_ == null) {
          control_ = null;
          onChanged();
        } else {
          control_ = null;
          controlBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * body
       * </pre>
       *
       * <code>.protocol.ControlMessage Control = 5;</code>
       */
      public com.ones.openplatform.protocol.Control.ControlMessage.Builder getControlBuilder() {
        
        onChanged();
        return getControlFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * body
       * </pre>
       *
       * <code>.protocol.ControlMessage Control = 5;</code>
       */
      public com.ones.openplatform.protocol.Control.ControlMessageOrBuilder getControlOrBuilder() {
        if (controlBuilder_ != null) {
          return controlBuilder_.getMessageOrBuilder();
        } else {
          return control_ == null ?
              com.ones.openplatform.protocol.Control.ControlMessage.getDefaultInstance() : control_;
        }
      }
      /**
       * <pre>
       * body
       * </pre>
       *
       * <code>.protocol.ControlMessage Control = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Control.ControlMessage, com.ones.openplatform.protocol.Control.ControlMessage.Builder, com.ones.openplatform.protocol.Control.ControlMessageOrBuilder> 
          getControlFieldBuilder() {
        if (controlBuilder_ == null) {
          controlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ones.openplatform.protocol.Control.ControlMessage, com.ones.openplatform.protocol.Control.ControlMessage.Builder, com.ones.openplatform.protocol.Control.ControlMessageOrBuilder>(
                  getControl(),
                  getParentForChildren(),
                  isClean());
          control_ = null;
        }
        return controlBuilder_;
      }

      private com.ones.openplatform.protocol.Plugin.PluginMessage plugin_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Plugin.PluginMessage, com.ones.openplatform.protocol.Plugin.PluginMessage.Builder, com.ones.openplatform.protocol.Plugin.PluginMessageOrBuilder> pluginBuilder_;
      /**
       * <code>.protocol.PluginMessage Plugin = 10;</code>
       * @return Whether the plugin field is set.
       */
      public boolean hasPlugin() {
        return pluginBuilder_ != null || plugin_ != null;
      }
      /**
       * <code>.protocol.PluginMessage Plugin = 10;</code>
       * @return The plugin.
       */
      public com.ones.openplatform.protocol.Plugin.PluginMessage getPlugin() {
        if (pluginBuilder_ == null) {
          return plugin_ == null ? com.ones.openplatform.protocol.Plugin.PluginMessage.getDefaultInstance() : plugin_;
        } else {
          return pluginBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.PluginMessage Plugin = 10;</code>
       */
      public Builder setPlugin(com.ones.openplatform.protocol.Plugin.PluginMessage value) {
        if (pluginBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          plugin_ = value;
          onChanged();
        } else {
          pluginBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protocol.PluginMessage Plugin = 10;</code>
       */
      public Builder setPlugin(
          com.ones.openplatform.protocol.Plugin.PluginMessage.Builder builderForValue) {
        if (pluginBuilder_ == null) {
          plugin_ = builderForValue.build();
          onChanged();
        } else {
          pluginBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protocol.PluginMessage Plugin = 10;</code>
       */
      public Builder mergePlugin(com.ones.openplatform.protocol.Plugin.PluginMessage value) {
        if (pluginBuilder_ == null) {
          if (plugin_ != null) {
            plugin_ =
              com.ones.openplatform.protocol.Plugin.PluginMessage.newBuilder(plugin_).mergeFrom(value).buildPartial();
          } else {
            plugin_ = value;
          }
          onChanged();
        } else {
          pluginBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protocol.PluginMessage Plugin = 10;</code>
       */
      public Builder clearPlugin() {
        if (pluginBuilder_ == null) {
          plugin_ = null;
          onChanged();
        } else {
          plugin_ = null;
          pluginBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protocol.PluginMessage Plugin = 10;</code>
       */
      public com.ones.openplatform.protocol.Plugin.PluginMessage.Builder getPluginBuilder() {
        
        onChanged();
        return getPluginFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.PluginMessage Plugin = 10;</code>
       */
      public com.ones.openplatform.protocol.Plugin.PluginMessageOrBuilder getPluginOrBuilder() {
        if (pluginBuilder_ != null) {
          return pluginBuilder_.getMessageOrBuilder();
        } else {
          return plugin_ == null ?
              com.ones.openplatform.protocol.Plugin.PluginMessage.getDefaultInstance() : plugin_;
        }
      }
      /**
       * <code>.protocol.PluginMessage Plugin = 10;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Plugin.PluginMessage, com.ones.openplatform.protocol.Plugin.PluginMessage.Builder, com.ones.openplatform.protocol.Plugin.PluginMessageOrBuilder> 
          getPluginFieldBuilder() {
        if (pluginBuilder_ == null) {
          pluginBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ones.openplatform.protocol.Plugin.PluginMessage, com.ones.openplatform.protocol.Plugin.PluginMessage.Builder, com.ones.openplatform.protocol.Plugin.PluginMessageOrBuilder>(
                  getPlugin(),
                  getParentForChildren(),
                  isClean());
          plugin_ = null;
        }
        return pluginBuilder_;
      }

      private com.ones.openplatform.protocol.Cmdb.CmdbMessage cmdb_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Cmdb.CmdbMessage, com.ones.openplatform.protocol.Cmdb.CmdbMessage.Builder, com.ones.openplatform.protocol.Cmdb.CmdbMessageOrBuilder> cmdbBuilder_;
      /**
       * <code>.protocol.CmdbMessage Cmdb = 15;</code>
       * @return Whether the cmdb field is set.
       */
      public boolean hasCmdb() {
        return cmdbBuilder_ != null || cmdb_ != null;
      }
      /**
       * <code>.protocol.CmdbMessage Cmdb = 15;</code>
       * @return The cmdb.
       */
      public com.ones.openplatform.protocol.Cmdb.CmdbMessage getCmdb() {
        if (cmdbBuilder_ == null) {
          return cmdb_ == null ? com.ones.openplatform.protocol.Cmdb.CmdbMessage.getDefaultInstance() : cmdb_;
        } else {
          return cmdbBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.CmdbMessage Cmdb = 15;</code>
       */
      public Builder setCmdb(com.ones.openplatform.protocol.Cmdb.CmdbMessage value) {
        if (cmdbBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cmdb_ = value;
          onChanged();
        } else {
          cmdbBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protocol.CmdbMessage Cmdb = 15;</code>
       */
      public Builder setCmdb(
          com.ones.openplatform.protocol.Cmdb.CmdbMessage.Builder builderForValue) {
        if (cmdbBuilder_ == null) {
          cmdb_ = builderForValue.build();
          onChanged();
        } else {
          cmdbBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protocol.CmdbMessage Cmdb = 15;</code>
       */
      public Builder mergeCmdb(com.ones.openplatform.protocol.Cmdb.CmdbMessage value) {
        if (cmdbBuilder_ == null) {
          if (cmdb_ != null) {
            cmdb_ =
              com.ones.openplatform.protocol.Cmdb.CmdbMessage.newBuilder(cmdb_).mergeFrom(value).buildPartial();
          } else {
            cmdb_ = value;
          }
          onChanged();
        } else {
          cmdbBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protocol.CmdbMessage Cmdb = 15;</code>
       */
      public Builder clearCmdb() {
        if (cmdbBuilder_ == null) {
          cmdb_ = null;
          onChanged();
        } else {
          cmdb_ = null;
          cmdbBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protocol.CmdbMessage Cmdb = 15;</code>
       */
      public com.ones.openplatform.protocol.Cmdb.CmdbMessage.Builder getCmdbBuilder() {
        
        onChanged();
        return getCmdbFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.CmdbMessage Cmdb = 15;</code>
       */
      public com.ones.openplatform.protocol.Cmdb.CmdbMessageOrBuilder getCmdbOrBuilder() {
        if (cmdbBuilder_ != null) {
          return cmdbBuilder_.getMessageOrBuilder();
        } else {
          return cmdb_ == null ?
              com.ones.openplatform.protocol.Cmdb.CmdbMessage.getDefaultInstance() : cmdb_;
        }
      }
      /**
       * <code>.protocol.CmdbMessage Cmdb = 15;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Cmdb.CmdbMessage, com.ones.openplatform.protocol.Cmdb.CmdbMessage.Builder, com.ones.openplatform.protocol.Cmdb.CmdbMessageOrBuilder> 
          getCmdbFieldBuilder() {
        if (cmdbBuilder_ == null) {
          cmdbBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ones.openplatform.protocol.Cmdb.CmdbMessage, com.ones.openplatform.protocol.Cmdb.CmdbMessage.Builder, com.ones.openplatform.protocol.Cmdb.CmdbMessageOrBuilder>(
                  getCmdb(),
                  getParentForChildren(),
                  isClean());
          cmdb_ = null;
        }
        return cmdbBuilder_;
      }

      private com.ones.openplatform.protocol.Resources.ResourceMessage resource_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Resources.ResourceMessage, com.ones.openplatform.protocol.Resources.ResourceMessage.Builder, com.ones.openplatform.protocol.Resources.ResourceMessageOrBuilder> resourceBuilder_;
      /**
       * <code>.protocol.ResourceMessage Resource = 20;</code>
       * @return Whether the resource field is set.
       */
      public boolean hasResource() {
        return resourceBuilder_ != null || resource_ != null;
      }
      /**
       * <code>.protocol.ResourceMessage Resource = 20;</code>
       * @return The resource.
       */
      public com.ones.openplatform.protocol.Resources.ResourceMessage getResource() {
        if (resourceBuilder_ == null) {
          return resource_ == null ? com.ones.openplatform.protocol.Resources.ResourceMessage.getDefaultInstance() : resource_;
        } else {
          return resourceBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.ResourceMessage Resource = 20;</code>
       */
      public Builder setResource(com.ones.openplatform.protocol.Resources.ResourceMessage value) {
        if (resourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resource_ = value;
          onChanged();
        } else {
          resourceBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protocol.ResourceMessage Resource = 20;</code>
       */
      public Builder setResource(
          com.ones.openplatform.protocol.Resources.ResourceMessage.Builder builderForValue) {
        if (resourceBuilder_ == null) {
          resource_ = builderForValue.build();
          onChanged();
        } else {
          resourceBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protocol.ResourceMessage Resource = 20;</code>
       */
      public Builder mergeResource(com.ones.openplatform.protocol.Resources.ResourceMessage value) {
        if (resourceBuilder_ == null) {
          if (resource_ != null) {
            resource_ =
              com.ones.openplatform.protocol.Resources.ResourceMessage.newBuilder(resource_).mergeFrom(value).buildPartial();
          } else {
            resource_ = value;
          }
          onChanged();
        } else {
          resourceBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protocol.ResourceMessage Resource = 20;</code>
       */
      public Builder clearResource() {
        if (resourceBuilder_ == null) {
          resource_ = null;
          onChanged();
        } else {
          resource_ = null;
          resourceBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protocol.ResourceMessage Resource = 20;</code>
       */
      public com.ones.openplatform.protocol.Resources.ResourceMessage.Builder getResourceBuilder() {
        
        onChanged();
        return getResourceFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.ResourceMessage Resource = 20;</code>
       */
      public com.ones.openplatform.protocol.Resources.ResourceMessageOrBuilder getResourceOrBuilder() {
        if (resourceBuilder_ != null) {
          return resourceBuilder_.getMessageOrBuilder();
        } else {
          return resource_ == null ?
              com.ones.openplatform.protocol.Resources.ResourceMessage.getDefaultInstance() : resource_;
        }
      }
      /**
       * <code>.protocol.ResourceMessage Resource = 20;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Resources.ResourceMessage, com.ones.openplatform.protocol.Resources.ResourceMessage.Builder, com.ones.openplatform.protocol.Resources.ResourceMessageOrBuilder> 
          getResourceFieldBuilder() {
        if (resourceBuilder_ == null) {
          resourceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ones.openplatform.protocol.Resources.ResourceMessage, com.ones.openplatform.protocol.Resources.ResourceMessage.Builder, com.ones.openplatform.protocol.Resources.ResourceMessageOrBuilder>(
                  getResource(),
                  getParentForChildren(),
                  isClean());
          resource_ = null;
        }
        return resourceBuilder_;
      }

      private com.ones.openplatform.protocol.Notify.NotifyMessage notify_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Notify.NotifyMessage, com.ones.openplatform.protocol.Notify.NotifyMessage.Builder, com.ones.openplatform.protocol.Notify.NotifyMessageOrBuilder> notifyBuilder_;
      /**
       * <code>.protocol.NotifyMessage Notify = 25;</code>
       * @return Whether the notify field is set.
       */
      public boolean hasNotify() {
        return notifyBuilder_ != null || notify_ != null;
      }
      /**
       * <code>.protocol.NotifyMessage Notify = 25;</code>
       * @return The notify.
       */
      public com.ones.openplatform.protocol.Notify.NotifyMessage getNotify() {
        if (notifyBuilder_ == null) {
          return notify_ == null ? com.ones.openplatform.protocol.Notify.NotifyMessage.getDefaultInstance() : notify_;
        } else {
          return notifyBuilder_.getMessage();
        }
      }
      /**
       * <code>.protocol.NotifyMessage Notify = 25;</code>
       */
      public Builder setNotify(com.ones.openplatform.protocol.Notify.NotifyMessage value) {
        if (notifyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          notify_ = value;
          onChanged();
        } else {
          notifyBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protocol.NotifyMessage Notify = 25;</code>
       */
      public Builder setNotify(
          com.ones.openplatform.protocol.Notify.NotifyMessage.Builder builderForValue) {
        if (notifyBuilder_ == null) {
          notify_ = builderForValue.build();
          onChanged();
        } else {
          notifyBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protocol.NotifyMessage Notify = 25;</code>
       */
      public Builder mergeNotify(com.ones.openplatform.protocol.Notify.NotifyMessage value) {
        if (notifyBuilder_ == null) {
          if (notify_ != null) {
            notify_ =
              com.ones.openplatform.protocol.Notify.NotifyMessage.newBuilder(notify_).mergeFrom(value).buildPartial();
          } else {
            notify_ = value;
          }
          onChanged();
        } else {
          notifyBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protocol.NotifyMessage Notify = 25;</code>
       */
      public Builder clearNotify() {
        if (notifyBuilder_ == null) {
          notify_ = null;
          onChanged();
        } else {
          notify_ = null;
          notifyBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protocol.NotifyMessage Notify = 25;</code>
       */
      public com.ones.openplatform.protocol.Notify.NotifyMessage.Builder getNotifyBuilder() {
        
        onChanged();
        return getNotifyFieldBuilder().getBuilder();
      }
      /**
       * <code>.protocol.NotifyMessage Notify = 25;</code>
       */
      public com.ones.openplatform.protocol.Notify.NotifyMessageOrBuilder getNotifyOrBuilder() {
        if (notifyBuilder_ != null) {
          return notifyBuilder_.getMessageOrBuilder();
        } else {
          return notify_ == null ?
              com.ones.openplatform.protocol.Notify.NotifyMessage.getDefaultInstance() : notify_;
        }
      }
      /**
       * <code>.protocol.NotifyMessage Notify = 25;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ones.openplatform.protocol.Notify.NotifyMessage, com.ones.openplatform.protocol.Notify.NotifyMessage.Builder, com.ones.openplatform.protocol.Notify.NotifyMessageOrBuilder> 
          getNotifyFieldBuilder() {
        if (notifyBuilder_ == null) {
          notifyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ones.openplatform.protocol.Notify.NotifyMessage, com.ones.openplatform.protocol.Notify.NotifyMessage.Builder, com.ones.openplatform.protocol.Notify.NotifyMessageOrBuilder>(
                  getNotify(),
                  getParentForChildren(),
                  isClean());
          notify_ = null;
        }
        return notifyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.PlatformMessage)
    }

    // @@protoc_insertion_point(class_scope:protocol.PlatformMessage)
    private static final com.ones.openplatform.protocol.Message.PlatformMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ones.openplatform.protocol.Message.PlatformMessage();
    }

    public static com.ones.openplatform.protocol.Message.PlatformMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlatformMessage>
        PARSER = new com.google.protobuf.AbstractParser<PlatformMessage>() {
      @java.lang.Override
      public PlatformMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlatformMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlatformMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlatformMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ones.openplatform.protocol.Message.PlatformMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_PlatformMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_PlatformMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\010protocol\032\017resources.pro" +
      "to\032\014plugin.proto\032\014common.proto\032\rcontrol." +
      "proto\032\ncmdb.proto\032\014notify.proto\"\211\002\n\017Plat" +
      "formMessage\022\'\n\006Header\030\001 \001(\0132\027.protocol.R" +
      "outerMessage\022)\n\007Control\030\005 \001(\0132\030.protocol" +
      ".ControlMessage\022\'\n\006Plugin\030\n \001(\0132\027.protoc" +
      "ol.PluginMessage\022#\n\004Cmdb\030\017 \001(\0132\025.protoco" +
      "l.CmdbMessage\022+\n\010Resource\030\024 \001(\0132\031.protoc" +
      "ol.ResourceMessage\022\'\n\006Notify\030\031 \001(\0132\027.pro" +
      "tocol.NotifyMessageB \n\036com.ones.openplat" +
      "form.protocolb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ones.openplatform.protocol.Resources.getDescriptor(),
          com.ones.openplatform.protocol.Plugin.getDescriptor(),
          com.ones.openplatform.protocol.Common.getDescriptor(),
          com.ones.openplatform.protocol.Control.getDescriptor(),
          com.ones.openplatform.protocol.Cmdb.getDescriptor(),
          com.ones.openplatform.protocol.Notify.getDescriptor(),
        });
    internal_static_protocol_PlatformMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_PlatformMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_PlatformMessage_descriptor,
        new java.lang.String[] { "Header", "Control", "Plugin", "Cmdb", "Resource", "Notify", });
    com.ones.openplatform.protocol.Resources.getDescriptor();
    com.ones.openplatform.protocol.Plugin.getDescriptor();
    com.ones.openplatform.protocol.Common.getDescriptor();
    com.ones.openplatform.protocol.Control.getDescriptor();
    com.ones.openplatform.protocol.Cmdb.getDescriptor();
    com.ones.openplatform.protocol.Notify.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
