// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.ones.protocol.example;

/**
 * <pre>
 * Our address book file is just one of these.
 * </pre>
 * <p>
 * Protobuf type {@code tutorial.AddressBook}
 */
public final class AddressBook extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.AddressBook)
    AddressBookOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use AddressBook.newBuilder() to construct.
  private AddressBook(final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private AddressBook() {
    this.people_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      final UnusedPrivateParameter unused) {
    return new AddressBook();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private AddressBook(
      final com.google.protobuf.CodedInputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    final com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        final int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              this.people_ = new java.util.ArrayList<Person>();
              mutable_bitField0_ |= 0x00000001;
            }
            this.people_.add(
                input.readMessage(Person.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!this.parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (final java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        this.people_ = java.util.Collections.unmodifiableList(this.people_);
      }
      this.unknownFields = unknownFields.build();
      this.makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return AddressBookProtos.internal_static_tutorial_AddressBook_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return AddressBookProtos.internal_static_tutorial_AddressBook_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AddressBook.class, AddressBook.Builder.class);
  }

  public static final int PEOPLE_FIELD_NUMBER = 1;
  private java.util.List<Person> people_;

  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  @java.lang.Override
  public java.util.List<Person> getPeopleList() {
    return this.people_;
  }

  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends PersonOrBuilder>
  getPeopleOrBuilderList() {
    return this.people_;
  }

  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  @java.lang.Override
  public int getPeopleCount() {
    return this.people_.size();
  }

  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  @java.lang.Override
  public Person getPeople(final int index) {
    return this.people_.get(index);
  }

  /**
   * <code>repeated .tutorial.Person people = 1;</code>
   */
  @java.lang.Override
  public PersonOrBuilder getPeopleOrBuilder(
      final int index) {
    return this.people_.get(index);
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    final byte isInitialized = this.memoizedIsInitialized;
    if (isInitialized == 1) {
      return true;
    }
    if (isInitialized == 0) {
      return false;
    }

    this.memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(final com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    for (final Person person : this.people_) {
      output.writeMessage(1, person);
    }
    this.unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = this.memoizedSize;
    if (size != -1) {
      return size;
    }

    size = 0;
    for (int i = 0; i < this.people_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, this.people_.get(i));
    }
    size += this.unknownFields.getSerializedSize();
    this.memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof AddressBook)) {
      return super.equals(obj);
    }
    final AddressBook other = (AddressBook) obj;

    if (!this.getPeopleList()
        .equals(other.getPeopleList())) {
      return false;
    }
    if (!this.unknownFields.equals(other.unknownFields)) {
      return false;
    }
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (this.memoizedHashCode != 0) {
      return this.memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (this.getPeopleCount() > 0) {
      hash = (37 * hash) + PEOPLE_FIELD_NUMBER;
      hash = (53 * hash) + this.getPeopleList().hashCode();
    }
    hash = (29 * hash) + this.unknownFields.hashCode();
    this.memoizedHashCode = hash;
    return hash;
  }

  public static AddressBook parseFrom(
      final java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static AddressBook parseFrom(
      final java.nio.ByteBuffer data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static AddressBook parseFrom(
      final com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static AddressBook parseFrom(
      final com.google.protobuf.ByteString data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static AddressBook parseFrom(final byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static AddressBook parseFrom(
      final byte[] data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static AddressBook parseFrom(final java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static AddressBook parseFrom(
      final java.io.InputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static AddressBook parseDelimitedFrom(final java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static AddressBook parseDelimitedFrom(
      final java.io.InputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static AddressBook parseFrom(
      final com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static AddressBook parseFrom(
      final com.google.protobuf.CodedInputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(final AddressBook prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    final Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * <pre>
   * Our address book file is just one of these.
   * </pre>
   * <p>
   * Protobuf type {@code tutorial.AddressBook}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.AddressBook)
      AddressBookOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return AddressBookProtos.internal_static_tutorial_AddressBook_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return AddressBookProtos.internal_static_tutorial_AddressBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AddressBook.class, AddressBook.Builder.class);
    }

    // Construct using com.ctlhub.zeromqpb.protocol.AddressBook.newBuilder()
    private Builder() {
      this.maybeForceBuilderInitialization();
    }

    private Builder(
        final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      this.maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        this.getPeopleFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (this.peopleBuilder_ == null) {
        this.people_ = java.util.Collections.emptyList();
        this.bitField0_ = (this.bitField0_ & ~0x00000001);
      } else {
        this.peopleBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return AddressBookProtos.internal_static_tutorial_AddressBook_descriptor;
    }

    @java.lang.Override
    public AddressBook getDefaultInstanceForType() {
      return AddressBook.getDefaultInstance();
    }

    @java.lang.Override
    public AddressBook build() {
      final AddressBook result = this.buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public AddressBook buildPartial() {
      final AddressBook result = new AddressBook(this);
      final int from_bitField0_ = this.bitField0_;
      if (this.peopleBuilder_ == null) {
        if (((this.bitField0_ & 0x00000001) != 0)) {
          this.people_ = java.util.Collections.unmodifiableList(this.people_);
          this.bitField0_ = (this.bitField0_ & ~0x00000001);
        }
        result.people_ = this.people_;
      } else {
        result.people_ = this.peopleBuilder_.build();
      }
      this.onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        final com.google.protobuf.Descriptors.FieldDescriptor field,
        final java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        final com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        final com.google.protobuf.Descriptors.FieldDescriptor field,
        final int index, final java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        final com.google.protobuf.Descriptors.FieldDescriptor field,
        final java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(final com.google.protobuf.Message other) {
      if (other instanceof AddressBook) {
        return this.mergeFrom((AddressBook) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(final AddressBook other) {
      if (other == AddressBook.getDefaultInstance()) {
        return this;
      }
      if (this.peopleBuilder_ == null) {
        if (!other.people_.isEmpty()) {
          if (this.people_.isEmpty()) {
            this.people_ = other.people_;
            this.bitField0_ = (this.bitField0_ & ~0x00000001);
          } else {
            this.ensurePeopleIsMutable();
            this.people_.addAll(other.people_);
          }
          this.onChanged();
        }
      } else {
        if (!other.people_.isEmpty()) {
          if (this.peopleBuilder_.isEmpty()) {
            this.peopleBuilder_.dispose();
            this.peopleBuilder_ = null;
            this.people_ = other.people_;
            this.bitField0_ = (this.bitField0_ & ~0x00000001);
            this.peopleBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                    this.getPeopleFieldBuilder() : null;
          } else {
            this.peopleBuilder_.addAllMessages(other.people_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      this.onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        final com.google.protobuf.CodedInputStream input,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AddressBook parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AddressBook) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          this.mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.util.List<Person> people_ =
        java.util.Collections.emptyList();

    private void ensurePeopleIsMutable() {
      if (!((this.bitField0_ & 0x00000001) != 0)) {
        this.people_ = new java.util.ArrayList<Person>(this.people_);
        this.bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Person, Person.Builder, PersonOrBuilder> peopleBuilder_;

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @Override
    public java.util.List<Person> getPeopleList() {
      if (this.peopleBuilder_ == null) {
        return java.util.Collections.unmodifiableList(this.people_);
      } else {
        return this.peopleBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @Override
    public int getPeopleCount() {
      if (this.peopleBuilder_ == null) {
        return this.people_.size();
      } else {
        return this.peopleBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @Override
    public Person getPeople(final int index) {
      if (this.peopleBuilder_ == null) {
        return this.people_.get(index);
      } else {
        return this.peopleBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Builder setPeople(
        final int index, final Person value) {
      if (this.peopleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.ensurePeopleIsMutable();
        this.people_.set(index, value);
        this.onChanged();
      } else {
        this.peopleBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Builder setPeople(
        final int index, final Person.Builder builderForValue) {
      if (this.peopleBuilder_ == null) {
        this.ensurePeopleIsMutable();
        this.people_.set(index, builderForValue.build());
        this.onChanged();
      } else {
        this.peopleBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Builder addPeople(final Person value) {
      if (this.peopleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.ensurePeopleIsMutable();
        this.people_.add(value);
        this.onChanged();
      } else {
        this.peopleBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Builder addPeople(
        final int index, final Person value) {
      if (this.peopleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.ensurePeopleIsMutable();
        this.people_.add(index, value);
        this.onChanged();
      } else {
        this.peopleBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Builder addPeople(
        final Person.Builder builderForValue) {
      if (this.peopleBuilder_ == null) {
        this.ensurePeopleIsMutable();
        this.people_.add(builderForValue.build());
        this.onChanged();
      } else {
        this.peopleBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Builder addPeople(
        final int index, final Person.Builder builderForValue) {
      if (this.peopleBuilder_ == null) {
        this.ensurePeopleIsMutable();
        this.people_.add(index, builderForValue.build());
        this.onChanged();
      } else {
        this.peopleBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Builder addAllPeople(
        final java.lang.Iterable<? extends Person> values) {
      if (this.peopleBuilder_ == null) {
        this.ensurePeopleIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, this.people_);
        this.onChanged();
      } else {
        this.peopleBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Builder clearPeople() {
      if (this.peopleBuilder_ == null) {
        this.people_ = java.util.Collections.emptyList();
        this.bitField0_ = (this.bitField0_ & ~0x00000001);
        this.onChanged();
      } else {
        this.peopleBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Builder removePeople(final int index) {
      if (this.peopleBuilder_ == null) {
        this.ensurePeopleIsMutable();
        this.people_.remove(index);
        this.onChanged();
      } else {
        this.peopleBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Person.Builder getPeopleBuilder(
        final int index) {
      return this.getPeopleFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @Override
    public PersonOrBuilder getPeopleOrBuilder(
        final int index) {
      if (this.peopleBuilder_ == null) {
        return this.people_.get(index);
      } else {
        return this.peopleBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    @Override
    public java.util.List<? extends PersonOrBuilder>
    getPeopleOrBuilderList() {
      if (this.peopleBuilder_ != null) {
        return this.peopleBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(this.people_);
      }
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Person.Builder addPeopleBuilder() {
      return this.getPeopleFieldBuilder().addBuilder(
          Person.getDefaultInstance());
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public Person.Builder addPeopleBuilder(
        final int index) {
      return this.getPeopleFieldBuilder().addBuilder(
          index, Person.getDefaultInstance());
    }

    /**
     * <code>repeated .tutorial.Person people = 1;</code>
     */
    public java.util.List<Person.Builder>
    getPeopleBuilderList() {
      return this.getPeopleFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Person, Person.Builder, PersonOrBuilder>
    getPeopleFieldBuilder() {
      if (this.peopleBuilder_ == null) {
        this.peopleBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Person, Person.Builder, PersonOrBuilder>(
            this.people_,
            ((this.bitField0_ & 0x00000001) != 0),
            this.getParentForChildren(),
            this.isClean());
        this.people_ = null;
      }
      return this.peopleBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:tutorial.AddressBook)
  }

  // @@protoc_insertion_point(class_scope:tutorial.AddressBook)
  private static final AddressBook DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new AddressBook();
  }

  public static AddressBook getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddressBook>
      PARSER = new com.google.protobuf.AbstractParser<AddressBook>() {
    @java.lang.Override
    public AddressBook parsePartialFrom(
        final com.google.protobuf.CodedInputStream input,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddressBook(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddressBook> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddressBook> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public AddressBook getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

