// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.ones.zeromqpb.example;

/**
 * <pre>
 * [START messages]
 * </pre>
 * <p>
 * Protobuf type {@code tutorial.Person}
 */
public final class Person extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tutorial.Person)
    PersonOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use Person.newBuilder() to construct.
  private Person(final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private Person() {
    this.name_ = "";
    this.email_ = "";
    this.phones_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      final UnusedPrivateParameter unused) {
    return new Person();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }

  private Person(
      final com.google.protobuf.CodedInputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    final com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        final int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            final java.lang.String s = input.readStringRequireUtf8();

            this.name_ = s;
            break;
          }
          case 16: {

            this.id_ = input.readInt32();
            break;
          }
          case 26: {
            final java.lang.String s = input.readStringRequireUtf8();

            this.email_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              this.phones_ = new java.util.ArrayList<Person.PhoneNumber>();
              mutable_bitField0_ |= 0x00000001;
            }
            this.phones_.add(
                input.readMessage(Person.PhoneNumber.parser(), extensionRegistry));
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (this.lastUpdated_ != null) {
              subBuilder = this.lastUpdated_.toBuilder();
            }
            this.lastUpdated_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(this.lastUpdated_);
              this.lastUpdated_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!this.parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (final java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        this.phones_ = java.util.Collections.unmodifiableList(this.phones_);
      }
      this.unknownFields = unknownFields.build();
      this.makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor
  getDescriptor() {
    return AddressBookProtos.internal_static_tutorial_Person_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
  internalGetFieldAccessorTable() {
    return AddressBookProtos.internal_static_tutorial_Person_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Person.class, Person.Builder.class);
  }

  /**
   * Protobuf enum {@code tutorial.Person.PhoneType}
   */
  public enum PhoneType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MOBILE = 0;</code>
     */
    MOBILE(0),
    /**
     * <code>HOME = 1;</code>
     */
    HOME(1),
    /**
     * <code>WORK = 2;</code>
     */
    WORK(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MOBILE = 0;</code>
     */
    public static final int MOBILE_VALUE = 0;
    /**
     * <code>HOME = 1;</code>
     */
    public static final int HOME_VALUE = 1;
    /**
     * <code>WORK = 2;</code>
     */
    public static final int WORK_VALUE = 2;

    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return this.value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PhoneType valueOf(final int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PhoneType forNumber(final int value) {
      switch (value) {
        case 0:
          return MOBILE;
        case 1:
          return HOME;
        case 2:
          return WORK;
        default:
          return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
    internalGetValueMap() {
      return internalValueMap;
    }

    private static final com.google.protobuf.Internal.EnumLiteMap<
        PhoneType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
          @Override
          public PhoneType findValueByNumber(final int number) {
            return PhoneType.forNumber(number);
          }
        };

    @Override
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
    getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(this.ordinal());
    }

    @Override
    public final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptorForType() {
      return getDescriptor();
    }

    public static final com.google.protobuf.Descriptors.EnumDescriptor
    getDescriptor() {
      return Person.getDescriptor().getEnumTypes().get(0);
    }

    private static final PhoneType[] VALUES = values();

    public static PhoneType valueOf(
        final com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PhoneType(final int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tutorial.Person.PhoneType)
  }

  public interface PhoneNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tutorial.Person.PhoneNumber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string number = 1;</code>
     *
     * @return The number.
     */
    java.lang.String getNumber();

    /**
     * <code>string number = 1;</code>
     *
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
    getNumberBytes();

    /**
     * <code>.tutorial.Person.PhoneType type = 2;</code>
     *
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();

    /**
     * <code>.tutorial.Person.PhoneType type = 2;</code>
     *
     * @return The type.
     */
    Person.PhoneType getType();
  }

  /**
   * Protobuf type {@code tutorial.Person.PhoneNumber}
   */
  public static final class PhoneNumber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tutorial.Person.PhoneNumber)
      PhoneNumberOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use PhoneNumber.newBuilder() to construct.
    private PhoneNumber(final com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private PhoneNumber() {
      this.number_ = "";
      this.type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        final UnusedPrivateParameter unused) {
      return new PhoneNumber();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    private PhoneNumber(
        final com.google.protobuf.CodedInputStream input,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      final com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          final int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              final java.lang.String s = input.readStringRequireUtf8();

              this.number_ = s;
              break;
            }
            case 16: {
              final int rawValue = input.readEnum();

              this.type_ = rawValue;
              break;
            }
            default: {
              if (!this.parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (final java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        this.makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return AddressBookProtos.internal_static_tutorial_Person_PhoneNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return AddressBookProtos.internal_static_tutorial_Person_PhoneNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.PhoneNumber.class, Person.PhoneNumber.Builder.class);
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object number_;

    /**
     * <code>string number = 1;</code>
     *
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      final java.lang.Object ref = this.number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        final com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        final java.lang.String s = bs.toStringUtf8();
        this.number_ = s;
        return s;
      }
    }

    /**
     * <code>string number = 1;</code>
     *
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getNumberBytes() {
      final java.lang.Object ref = this.number_;
      if (ref instanceof java.lang.String) {
        final com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        this.number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;

    /**
     * <code>.tutorial.Person.PhoneType type = 2;</code>
     *
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return this.type_;
    }

    /**
     * <code>.tutorial.Person.PhoneType type = 2;</code>
     *
     * @return The type.
     */
    @java.lang.Override
    public Person.PhoneType getType() {
      @SuppressWarnings("deprecation") final Person.PhoneType result = Person.PhoneType.valueOf(this.type_);
      return result == null ? Person.PhoneType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      final byte isInitialized = this.memoizedIsInitialized;
      if (isInitialized == 1) {
        return true;
      }
      if (isInitialized == 0) {
        return false;
      }

      this.memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(final com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (!this.getNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, this.number_);
      }
      if (this.type_ != Person.PhoneType.MOBILE.getNumber()) {
        output.writeEnum(2, this.type_);
      }
      this.unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = this.memoizedSize;
      if (size != -1) {
        return size;
      }

      size = 0;
      if (!this.getNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, this.number_);
      }
      if (this.type_ != Person.PhoneType.MOBILE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(2, this.type_);
      }
      size += this.unknownFields.getSerializedSize();
      this.memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof Person.PhoneNumber)) {
        return super.equals(obj);
      }
      final Person.PhoneNumber other = (Person.PhoneNumber) obj;

      if (!this.getNumber()
          .equals(other.getNumber())) {
        return false;
      }
      if (this.type_ != other.type_) {
        return false;
      }
      if (!this.unknownFields.equals(other.unknownFields)) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (this.memoizedHashCode != 0) {
        return this.memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + this.getNumber().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + this.type_;
      hash = (29 * hash) + this.unknownFields.hashCode();
      this.memoizedHashCode = hash;
      return hash;
    }

    public static Person.PhoneNumber parseFrom(
        final java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Person.PhoneNumber parseFrom(
        final java.nio.ByteBuffer data,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Person.PhoneNumber parseFrom(
        final com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Person.PhoneNumber parseFrom(
        final com.google.protobuf.ByteString data,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Person.PhoneNumber parseFrom(final byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static Person.PhoneNumber parseFrom(
        final byte[] data,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static Person.PhoneNumber parseFrom(final java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static Person.PhoneNumber parseFrom(
        final java.io.InputStream input,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Person.PhoneNumber parseDelimitedFrom(final java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Person.PhoneNumber parseDelimitedFrom(
        final java.io.InputStream input,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static Person.PhoneNumber parseFrom(
        final com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }

    public static Person.PhoneNumber parseFrom(
        final com.google.protobuf.CodedInputStream input,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(final Person.PhoneNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      final Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code tutorial.Person.PhoneNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tutorial.Person.PhoneNumber)
        Person.PhoneNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return AddressBookProtos.internal_static_tutorial_Person_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return AddressBookProtos.internal_static_tutorial_Person_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.PhoneNumber.class, Person.PhoneNumber.Builder.class);
      }

      // Construct using com.ctlhub.zeromqpb.protocol.Person.PhoneNumber.newBuilder()
      private Builder() {
        this.maybeForceBuilderInitialization();
      }

      private Builder(
          final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        this.maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
            .alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        this.number_ = "";

        this.type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return AddressBookProtos.internal_static_tutorial_Person_PhoneNumber_descriptor;
      }

      @java.lang.Override
      public Person.PhoneNumber getDefaultInstanceForType() {
        return Person.PhoneNumber.getDefaultInstance();
      }

      @java.lang.Override
      public Person.PhoneNumber build() {
        final Person.PhoneNumber result = this.buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Person.PhoneNumber buildPartial() {
        final Person.PhoneNumber result = new Person.PhoneNumber(this);
        result.number_ = this.number_;
        result.type_ = this.type_;
        this.onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          final com.google.protobuf.Descriptors.FieldDescriptor field,
          final java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
          final com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
          final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          final com.google.protobuf.Descriptors.FieldDescriptor field,
          final int index, final java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          final com.google.protobuf.Descriptors.FieldDescriptor field,
          final java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(final com.google.protobuf.Message other) {
        if (other instanceof Person.PhoneNumber) {
          return this.mergeFrom((Person.PhoneNumber) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(final Person.PhoneNumber other) {
        if (other == Person.PhoneNumber.getDefaultInstance()) {
          return this;
        }
        if (!other.getNumber().isEmpty()) {
          this.number_ = other.number_;
          this.onChanged();
        }
        if (other.type_ != 0) {
          this.setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        this.onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          final com.google.protobuf.CodedInputStream input,
          final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Person.PhoneNumber parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person.PhoneNumber) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            this.mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object number_ = "";

      /**
       * <code>string number = 1;</code>
       *
       * @return The number.
       */
      @Override
      public java.lang.String getNumber() {
        final java.lang.Object ref = this.number_;
        if (!(ref instanceof java.lang.String)) {
          final com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          final java.lang.String s = bs.toStringUtf8();
          this.number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string number = 1;</code>
       *
       * @return The bytes for number.
       */
      @Override
      public com.google.protobuf.ByteString
      getNumberBytes() {
        final java.lang.Object ref = this.number_;
        if (ref instanceof String) {
          final com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          this.number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string number = 1;</code>
       *
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          final java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        this.number_ = value;
        this.onChanged();
        return this;
      }

      /**
       * <code>string number = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearNumber() {

        this.number_ = getDefaultInstance().getNumber();
        this.onChanged();
        return this;
      }

      /**
       * <code>string number = 1;</code>
       *
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          final com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        this.number_ = value;
        this.onChanged();
        return this;
      }

      private int type_ = 0;

      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       *
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override
      public int getTypeValue() {
        return this.type_;
      }

      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       *
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(final int value) {

        this.type_ = value;
        this.onChanged();
        return this;
      }

      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       *
       * @return The type.
       */
      @java.lang.Override
      public Person.PhoneType getType() {
        @SuppressWarnings("deprecation") final Person.PhoneType result = Person.PhoneType.valueOf(this.type_);
        return result == null ? Person.PhoneType.UNRECOGNIZED : result;
      }

      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       *
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(final Person.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }

        this.type_ = value.getNumber();
        this.onChanged();
        return this;
      }

      /**
       * <code>.tutorial.Person.PhoneType type = 2;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearType() {

        this.type_ = 0;
        this.onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Person.PhoneNumber)
    }

    // @@protoc_insertion_point(class_scope:tutorial.Person.PhoneNumber)
    private static final Person.PhoneNumber DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new Person.PhoneNumber();
    }

    public static Person.PhoneNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneNumber>
        PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
      @java.lang.Override
      public PhoneNumber parsePartialFrom(
          final com.google.protobuf.CodedInputStream input,
          final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PhoneNumber(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PhoneNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Person.PhoneNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;

  /**
   * <code>string name = 1;</code>
   *
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    final java.lang.Object ref = this.name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      final com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      final java.lang.String s = bs.toStringUtf8();
      this.name_ = s;
      return s;
    }
  }

  /**
   * <code>string name = 1;</code>
   *
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getNameBytes() {
    final java.lang.Object ref = this.name_;
    if (ref instanceof java.lang.String) {
      final com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      this.name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int id_;

  /**
   * <pre>
   * Unique ID number for this person.
   * </pre>
   *
   * <code>int32 id = 2;</code>
   *
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return this.id_;
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  private volatile java.lang.Object email_;

  /**
   * <code>string email = 3;</code>
   *
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    final java.lang.Object ref = this.email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      final com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      final java.lang.String s = bs.toStringUtf8();
      this.email_ = s;
      return s;
    }
  }

  /**
   * <code>string email = 3;</code>
   *
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
  getEmailBytes() {
    final java.lang.Object ref = this.email_;
    if (ref instanceof java.lang.String) {
      final com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      this.email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONES_FIELD_NUMBER = 4;
  private java.util.List<Person.PhoneNumber> phones_;

  /**
   * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
   */
  @java.lang.Override
  public java.util.List<Person.PhoneNumber> getPhonesList() {
    return this.phones_;
  }

  /**
   * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends Person.PhoneNumberOrBuilder>
  getPhonesOrBuilderList() {
    return this.phones_;
  }

  /**
   * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
   */
  @java.lang.Override
  public int getPhonesCount() {
    return this.phones_.size();
  }

  /**
   * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
   */
  @java.lang.Override
  public Person.PhoneNumber getPhones(final int index) {
    return this.phones_.get(index);
  }

  /**
   * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
   */
  @java.lang.Override
  public Person.PhoneNumberOrBuilder getPhonesOrBuilder(
      final int index) {
    return this.phones_.get(index);
  }

  public static final int LAST_UPDATED_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp lastUpdated_;

  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   *
   * @return Whether the lastUpdated field is set.
   */
  @java.lang.Override
  public boolean hasLastUpdated() {
    return this.lastUpdated_ != null;
  }

  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   *
   * @return The lastUpdated.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLastUpdated() {
    return this.lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : this.lastUpdated_;
  }

  /**
   * <code>.google.protobuf.Timestamp last_updated = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
    return this.getLastUpdated();
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    final byte isInitialized = this.memoizedIsInitialized;
    if (isInitialized == 1) {
      return true;
    }
    if (isInitialized == 0) {
      return false;
    }

    this.memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(final com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (!this.getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, this.name_);
    }
    if (this.id_ != 0) {
      output.writeInt32(2, this.id_);
    }
    if (!this.getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, this.email_);
    }
    for (int i = 0; i < this.phones_.size(); i++) {
      output.writeMessage(4, this.phones_.get(i));
    }
    if (this.lastUpdated_ != null) {
      output.writeMessage(5, this.getLastUpdated());
    }
    this.unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = this.memoizedSize;
    if (size != -1) {
      return size;
    }

    size = 0;
    if (!this.getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, this.name_);
    }
    if (this.id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, this.id_);
    }
    if (!this.getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, this.email_);
    }
    for (int i = 0; i < this.phones_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, this.phones_.get(i));
    }
    if (this.lastUpdated_ != null) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, this.getLastUpdated());
    }
    size += this.unknownFields.getSerializedSize();
    this.memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof Person)) {
      return super.equals(obj);
    }
    final Person other = (Person) obj;

    if (!this.getName()
        .equals(other.getName())) {
      return false;
    }
    if (this.getId()
        != other.getId()) {
      return false;
    }
    if (!this.getEmail()
        .equals(other.getEmail())) {
      return false;
    }
    if (!this.getPhonesList()
        .equals(other.getPhonesList())) {
      return false;
    }
    if (this.hasLastUpdated() != other.hasLastUpdated()) {
      return false;
    }
    if (this.hasLastUpdated()) {
      if (!this.getLastUpdated()
          .equals(other.getLastUpdated())) {
        return false;
      }
    }
    if (!this.unknownFields.equals(other.unknownFields)) {
      return false;
    }
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (this.memoizedHashCode != 0) {
      return this.memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + this.getName().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + this.getId();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + this.getEmail().hashCode();
    if (this.getPhonesCount() > 0) {
      hash = (37 * hash) + PHONES_FIELD_NUMBER;
      hash = (53 * hash) + this.getPhonesList().hashCode();
    }
    if (this.hasLastUpdated()) {
      hash = (37 * hash) + LAST_UPDATED_FIELD_NUMBER;
      hash = (53 * hash) + this.getLastUpdated().hashCode();
    }
    hash = (29 * hash) + this.unknownFields.hashCode();
    this.memoizedHashCode = hash;
    return hash;
  }

  public static Person parseFrom(
      final java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static Person parseFrom(
      final java.nio.ByteBuffer data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static Person parseFrom(
      final com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static Person parseFrom(
      final com.google.protobuf.ByteString data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static Person parseFrom(final byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static Person parseFrom(
      final byte[] data,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static Person parseFrom(final java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static Person parseFrom(
      final java.io.InputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static Person parseDelimitedFrom(final java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static Person parseDelimitedFrom(
      final java.io.InputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static Person parseFrom(
      final com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static Person parseFrom(
      final com.google.protobuf.CodedInputStream input,
      final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(final Person prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    final Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * <pre>
   * [START messages]
   * </pre>
   * <p>
   * Protobuf type {@code tutorial.Person}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tutorial.Person)
      PersonOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return AddressBookProtos.internal_static_tutorial_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return AddressBookProtos.internal_static_tutorial_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.class, Person.Builder.class);
    }

    // Construct using com.ctlhub.zeromqpb.protocol.Person.newBuilder()
    private Builder() {
      this.maybeForceBuilderInitialization();
    }

    private Builder(
        final com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      this.maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
          .alwaysUseFieldBuilders) {
        this.getPhonesFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      this.name_ = "";

      this.id_ = 0;

      this.email_ = "";

      if (this.phonesBuilder_ == null) {
        this.phones_ = java.util.Collections.emptyList();
        this.bitField0_ = (this.bitField0_ & ~0x00000001);
      } else {
        this.phonesBuilder_.clear();
      }
      if (this.lastUpdatedBuilder_ == null) {
        this.lastUpdated_ = null;
      } else {
        this.lastUpdated_ = null;
        this.lastUpdatedBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
    getDescriptorForType() {
      return AddressBookProtos.internal_static_tutorial_Person_descriptor;
    }

    @java.lang.Override
    public Person getDefaultInstanceForType() {
      return Person.getDefaultInstance();
    }

    @java.lang.Override
    public Person build() {
      final Person result = this.buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Person buildPartial() {
      final Person result = new Person(this);
      final int from_bitField0_ = this.bitField0_;
      result.name_ = this.name_;
      result.id_ = this.id_;
      result.email_ = this.email_;
      if (this.phonesBuilder_ == null) {
        if (((this.bitField0_ & 0x00000001) != 0)) {
          this.phones_ = java.util.Collections.unmodifiableList(this.phones_);
          this.bitField0_ = (this.bitField0_ & ~0x00000001);
        }
        result.phones_ = this.phones_;
      } else {
        result.phones_ = this.phonesBuilder_.build();
      }
      if (this.lastUpdatedBuilder_ == null) {
        result.lastUpdated_ = this.lastUpdated_;
      } else {
        result.lastUpdated_ = this.lastUpdatedBuilder_.build();
      }
      this.onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        final com.google.protobuf.Descriptors.FieldDescriptor field,
        final java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        final com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        final com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        final com.google.protobuf.Descriptors.FieldDescriptor field,
        final int index, final java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        final com.google.protobuf.Descriptors.FieldDescriptor field,
        final java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(final com.google.protobuf.Message other) {
      if (other instanceof Person) {
        return this.mergeFrom((Person) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(final Person other) {
      if (other == Person.getDefaultInstance()) {
        return this;
      }
      if (!other.getName().isEmpty()) {
        this.name_ = other.name_;
        this.onChanged();
      }
      if (other.getId() != 0) {
        this.setId(other.getId());
      }
      if (!other.getEmail().isEmpty()) {
        this.email_ = other.email_;
        this.onChanged();
      }
      if (this.phonesBuilder_ == null) {
        if (!other.phones_.isEmpty()) {
          if (this.phones_.isEmpty()) {
            this.phones_ = other.phones_;
            this.bitField0_ = (this.bitField0_ & ~0x00000001);
          } else {
            this.ensurePhonesIsMutable();
            this.phones_.addAll(other.phones_);
          }
          this.onChanged();
        }
      } else {
        if (!other.phones_.isEmpty()) {
          if (this.phonesBuilder_.isEmpty()) {
            this.phonesBuilder_.dispose();
            this.phonesBuilder_ = null;
            this.phones_ = other.phones_;
            this.bitField0_ = (this.bitField0_ & ~0x00000001);
            this.phonesBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                    this.getPhonesFieldBuilder() : null;
          } else {
            this.phonesBuilder_.addAllMessages(other.phones_);
          }
        }
      }
      if (other.hasLastUpdated()) {
        this.mergeLastUpdated(other.getLastUpdated());
      }
      this.mergeUnknownFields(other.unknownFields);
      this.onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        final com.google.protobuf.CodedInputStream input,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Person parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Person) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          this.mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private java.lang.Object name_ = "";

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    @Override
    public java.lang.String getName() {
      final java.lang.Object ref = this.name_;
      if (!(ref instanceof java.lang.String)) {
        final com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        final java.lang.String s = bs.toStringUtf8();
        this.name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
    getNameBytes() {
      final java.lang.Object ref = this.name_;
      if (ref instanceof String) {
        final com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        this.name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string name = 1;</code>
     *
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        final java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      this.name_ = value;
      this.onChanged();
      return this;
    }

    /**
     * <code>string name = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearName() {

      this.name_ = getDefaultInstance().getName();
      this.onChanged();
      return this;
    }

    /**
     * <code>string name = 1;</code>
     *
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        final com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      this.name_ = value;
      this.onChanged();
      return this;
    }

    private int id_;

    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>int32 id = 2;</code>
     *
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return this.id_;
    }

    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>int32 id = 2;</code>
     *
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(final int value) {

      this.id_ = value;
      this.onChanged();
      return this;
    }

    /**
     * <pre>
     * Unique ID number for this person.
     * </pre>
     *
     * <code>int32 id = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearId() {

      this.id_ = 0;
      this.onChanged();
      return this;
    }

    private java.lang.Object email_ = "";

    /**
     * <code>string email = 3;</code>
     *
     * @return The email.
     */
    @Override
    public java.lang.String getEmail() {
      final java.lang.Object ref = this.email_;
      if (!(ref instanceof java.lang.String)) {
        final com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        final java.lang.String s = bs.toStringUtf8();
        this.email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string email = 3;</code>
     *
     * @return The bytes for email.
     */
    @Override
    public com.google.protobuf.ByteString
    getEmailBytes() {
      final java.lang.Object ref = this.email_;
      if (ref instanceof String) {
        final com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        this.email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string email = 3;</code>
     *
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        final java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      this.email_ = value;
      this.onChanged();
      return this;
    }

    /**
     * <code>string email = 3;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearEmail() {

      this.email_ = getDefaultInstance().getEmail();
      this.onChanged();
      return this;
    }

    /**
     * <code>string email = 3;</code>
     *
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        final com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      this.email_ = value;
      this.onChanged();
      return this;
    }

    private java.util.List<Person.PhoneNumber> phones_ =
        java.util.Collections.emptyList();

    private void ensurePhonesIsMutable() {
      if (!((this.bitField0_ & 0x00000001) != 0)) {
        this.phones_ = new java.util.ArrayList<Person.PhoneNumber>(this.phones_);
        this.bitField0_ |= 0x00000001;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Person.PhoneNumber, Person.PhoneNumber.Builder, Person.PhoneNumberOrBuilder> phonesBuilder_;

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    @Override
    public java.util.List<Person.PhoneNumber> getPhonesList() {
      if (this.phonesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(this.phones_);
      } else {
        return this.phonesBuilder_.getMessageList();
      }
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    @Override
    public int getPhonesCount() {
      if (this.phonesBuilder_ == null) {
        return this.phones_.size();
      } else {
        return this.phonesBuilder_.getCount();
      }
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    @Override
    public Person.PhoneNumber getPhones(final int index) {
      if (this.phonesBuilder_ == null) {
        return this.phones_.get(index);
      } else {
        return this.phonesBuilder_.getMessage(index);
      }
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Builder setPhones(
        final int index, final Person.PhoneNumber value) {
      if (this.phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.ensurePhonesIsMutable();
        this.phones_.set(index, value);
        this.onChanged();
      } else {
        this.phonesBuilder_.setMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Builder setPhones(
        final int index, final Person.PhoneNumber.Builder builderForValue) {
      if (this.phonesBuilder_ == null) {
        this.ensurePhonesIsMutable();
        this.phones_.set(index, builderForValue.build());
        this.onChanged();
      } else {
        this.phonesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Builder addPhones(final Person.PhoneNumber value) {
      if (this.phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.ensurePhonesIsMutable();
        this.phones_.add(value);
        this.onChanged();
      } else {
        this.phonesBuilder_.addMessage(value);
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Builder addPhones(
        final int index, final Person.PhoneNumber value) {
      if (this.phonesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.ensurePhonesIsMutable();
        this.phones_.add(index, value);
        this.onChanged();
      } else {
        this.phonesBuilder_.addMessage(index, value);
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Builder addPhones(
        final Person.PhoneNumber.Builder builderForValue) {
      if (this.phonesBuilder_ == null) {
        this.ensurePhonesIsMutable();
        this.phones_.add(builderForValue.build());
        this.onChanged();
      } else {
        this.phonesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Builder addPhones(
        final int index, final Person.PhoneNumber.Builder builderForValue) {
      if (this.phonesBuilder_ == null) {
        this.ensurePhonesIsMutable();
        this.phones_.add(index, builderForValue.build());
        this.onChanged();
      } else {
        this.phonesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Builder addAllPhones(
        final java.lang.Iterable<? extends Person.PhoneNumber> values) {
      if (this.phonesBuilder_ == null) {
        this.ensurePhonesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, this.phones_);
        this.onChanged();
      } else {
        this.phonesBuilder_.addAllMessages(values);
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Builder clearPhones() {
      if (this.phonesBuilder_ == null) {
        this.phones_ = java.util.Collections.emptyList();
        this.bitField0_ = (this.bitField0_ & ~0x00000001);
        this.onChanged();
      } else {
        this.phonesBuilder_.clear();
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Builder removePhones(final int index) {
      if (this.phonesBuilder_ == null) {
        this.ensurePhonesIsMutable();
        this.phones_.remove(index);
        this.onChanged();
      } else {
        this.phonesBuilder_.remove(index);
      }
      return this;
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Person.PhoneNumber.Builder getPhonesBuilder(
        final int index) {
      return this.getPhonesFieldBuilder().getBuilder(index);
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    @Override
    public Person.PhoneNumberOrBuilder getPhonesOrBuilder(
        final int index) {
      if (this.phonesBuilder_ == null) {
        return this.phones_.get(index);
      } else {
        return this.phonesBuilder_.getMessageOrBuilder(index);
      }
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    @Override
    public java.util.List<? extends Person.PhoneNumberOrBuilder>
    getPhonesOrBuilderList() {
      if (this.phonesBuilder_ != null) {
        return this.phonesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(this.phones_);
      }
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Person.PhoneNumber.Builder addPhonesBuilder() {
      return this.getPhonesFieldBuilder().addBuilder(
          Person.PhoneNumber.getDefaultInstance());
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public Person.PhoneNumber.Builder addPhonesBuilder(
        final int index) {
      return this.getPhonesFieldBuilder().addBuilder(
          index, Person.PhoneNumber.getDefaultInstance());
    }

    /**
     * <code>repeated .tutorial.Person.PhoneNumber phones = 4;</code>
     */
    public java.util.List<Person.PhoneNumber.Builder>
    getPhonesBuilderList() {
      return this.getPhonesFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Person.PhoneNumber, Person.PhoneNumber.Builder, Person.PhoneNumberOrBuilder>
    getPhonesFieldBuilder() {
      if (this.phonesBuilder_ == null) {
        this.phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Person.PhoneNumber, Person.PhoneNumber.Builder, Person.PhoneNumberOrBuilder>(
            this.phones_,
            ((this.bitField0_ & 0x00000001) != 0),
            this.getParentForChildren(),
            this.isClean());
        this.phones_ = null;
      }
      return this.phonesBuilder_;
    }

    private com.google.protobuf.Timestamp lastUpdated_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdatedBuilder_;

    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     *
     * @return Whether the lastUpdated field is set.
     */
    @Override
    public boolean hasLastUpdated() {
      return this.lastUpdatedBuilder_ != null || this.lastUpdated_ != null;
    }

    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     *
     * @return The lastUpdated.
     */
    @Override
    public com.google.protobuf.Timestamp getLastUpdated() {
      if (this.lastUpdatedBuilder_ == null) {
        return this.lastUpdated_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : this.lastUpdated_;
      } else {
        return this.lastUpdatedBuilder_.getMessage();
      }
    }

    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder setLastUpdated(final com.google.protobuf.Timestamp value) {
      if (this.lastUpdatedBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        this.lastUpdated_ = value;
        this.onChanged();
      } else {
        this.lastUpdatedBuilder_.setMessage(value);
      }

      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder setLastUpdated(
        final com.google.protobuf.Timestamp.Builder builderForValue) {
      if (this.lastUpdatedBuilder_ == null) {
        this.lastUpdated_ = builderForValue.build();
        this.onChanged();
      } else {
        this.lastUpdatedBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder mergeLastUpdated(final com.google.protobuf.Timestamp value) {
      if (this.lastUpdatedBuilder_ == null) {
        if (this.lastUpdated_ != null) {
          this.lastUpdated_ =
              com.google.protobuf.Timestamp.newBuilder(this.lastUpdated_).mergeFrom(value).buildPartial();
        } else {
          this.lastUpdated_ = value;
        }
        this.onChanged();
      } else {
        this.lastUpdatedBuilder_.mergeFrom(value);
      }

      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    public Builder clearLastUpdated() {
      if (this.lastUpdatedBuilder_ == null) {
        this.lastUpdated_ = null;
        this.onChanged();
      } else {
        this.lastUpdated_ = null;
        this.lastUpdatedBuilder_ = null;
      }

      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastUpdatedBuilder() {

      this.onChanged();
      return this.getLastUpdatedFieldBuilder().getBuilder();
    }

    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    @Override
    public com.google.protobuf.TimestampOrBuilder getLastUpdatedOrBuilder() {
      if (this.lastUpdatedBuilder_ != null) {
        return this.lastUpdatedBuilder_.getMessageOrBuilder();
      } else {
        return this.lastUpdated_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : this.lastUpdated_;
      }
    }

    /**
     * <code>.google.protobuf.Timestamp last_updated = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>
    getLastUpdatedFieldBuilder() {
      if (this.lastUpdatedBuilder_ == null) {
        this.lastUpdatedBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
            this.getLastUpdated(),
            this.getParentForChildren(),
            this.isClean());
        this.lastUpdated_ = null;
      }
      return this.lastUpdatedBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:tutorial.Person)
  }

  // @@protoc_insertion_point(class_scope:tutorial.Person)
  private static final Person DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new Person();
  }

  public static Person getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Person>
      PARSER = new com.google.protobuf.AbstractParser<Person>() {
    @java.lang.Override
    public Person parsePartialFrom(
        final com.google.protobuf.CodedInputStream input,
        final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Person(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Person> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Person> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Person getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

